lang = {
	none: "",
	b_stone: "Kameň",
	b_coal: "Uhlie",
	b_iron: "Želzo",
	b_gold: "Zlato",
	b_diamond: "Diamant",
	b_emerald: "Emerald",
	b_obsidian: "Obsidián",
	b_cobalt: "Kobalt",
	item_none: "Holé ruky",
	abs_noName: "[Meno neznáme]",
	abs_dur: "Výdrž",
	abs_mineLevel: "Ťažobný level",
	abs_canBreak: "Rozbitelný",
	msg_blockNotMinable: "Block $1 sa nedá vyťažiť",
	msg_blockTooHard: "Nástroj $1 je príliž slabý aby vyťažil $2",
	msg_pickBroken: "$1 je rozbitý a nepoužitelný",
	msg_mined: "Vyťažené: $1, trvalo $2s",
	msg_itemBroken: "$1 rozbitý",
	msg_moved: "Pohyb trval $1s",
	msg_cannotMove: "Pohyb zablokovaný",
	msg_nothingSelected: "Žiadny nástroj zvolený",
	msg_moneyGot: "Získal si $1₪",
	hlp_playerMenu: "(p)",
	hlp_itemMenu: "Inven(t)ár",
	tile_air: "Vzduch",
	tile_stone: "Kameň",
	tile_coal_ore: "Uhelná ruda",
	tile_iron_ore: "Železná ruda",
	tile_gold_ore: "Zlatá ruda",
	tile_diamond_ore: "Diamantová ruda",
	tile_emerald_ore: "Emeraldové ruda",
	tile_cobalt_ore: "Kobaltová ruda",
	tile_obsidian_block: "Obsidiánový blok",
	tile_wall: "Stena",
	tile_comp_wall: "Boring™ Inc. Stena™",
	tile_clay: "Íl",
	tile_forceField: "Silové pole",
	tile_npc: "Človek",
	tile_table: "Stôl",
	tile_lootBox_money: "Tokenová krabica",
	mat_cobble: "Štrk",
	mat_coal_ore: "Uhlie",
	mat_iron_ore: "Železná ruda",
	mat_gold_ore: "Zlatá ruda",
	mat_diamond_ore: "Diamantový prach",
	mat_emerald_ore: "Emeraldový prach",
	mat_cobalt_ore: "Kobaltová ruda",
	mat_obsidian: "Obsidiánové črepy",
	mat_clay: "Íl",
	item_corpStonePick: "Boring™ Inc. Kamenný Krompáč™",
	item_stonePick: "Kamenný krompáč",
	item_ironPick: "Železný krompáč",
	item_goldPick: "Zlatý krompáč",
	item_diamondPick: "Diamantový krompáč",
	item_emeraldPick: "Emeraldový krompáč",
	item_obsidianPick: "Obsidiánový krompáč",
	item_cobaltPick: "Kobaltový krompáč",
	item_accessCard: "Prístupová karta",
	item_accessCard_desc: "Ako povadal manažér, nikam ťa nedostane.",
	event_tutorial_npc_greeter_name: "Uvýtavač",
	event_tutorial_npc_greeter_line_init: "Vytaj v Boring™ Inc. Mine N°42. Aktuálne sa nachádzame 48km pod povrchom zeme.",
	event_tutorial_npc_greeter_line_init_answer_whatNow: "Takže čo teraz?",
	event_tutorial_npc_greeter_line_init_answer_skip: "Môžme preskočiť tie formality?",
	event_tutorial_npc_greeter_line_init_answer_introduce: "[ Predstaviť sa ]",
	event_tutorial_npc_greeter_line_reqName: "Budem potrebovať tvoje meno.",
	event_tutorial_npc_greeter_line_reqName_answer_introduce: "[ Predstaviť sa ]",
	event_tutorial_npc_greeter_line_reqName_answer_decline: "Toje súkromná informácia.",
	event_tutorial_npc_greeter_line_decName: "Tak sa môžeš vrátiť odkial si prišiel.",
	event_tutorial_npc_greeter_line_decName_answer_giveUp: "OK, vzdávam sa... [Predstaviť sa]",
	event_tutorial_npc_greeter_line_personalQInt: "Takže $1, potrebujem ešte pár osobných informácií. Máš radšej mačky alebo psov?",
	event_tutorial_npc_greeter_line_personalQInt_answer_cat: "Mačky",
	event_tutorial_npc_greeter_line_personalQInt_answer_dog: "Psov",
	event_tutorial_npc_greeter_line_personalQOut: "Huh. Takéto niečo by som od teba nečakal.",
	event_tutorial_npc_greeter_line_personalQOut_answer_defensive: "Niečo zlé s mojím rozhodnutím?",
	event_tutorial_npc_greeter_line_personalQOut_answer_curious: "A čo si čakal?",
	event_tutorial_npc_greeter_line_final: "Ale nič... už ti otvorím pole. Pokračuj cez dvere napravo odtialto.",
	event_tutorial_npc_greeter_line_after: "Prečo si sa vrátil? Choď cez dvere napravo odtialto.",
	event_tutorial_npc_trainer_name: "Tréner",
	event_tutorial_npc_trainer_line_init: "To ale trvalo. Takže keď si už konečne prišiel trocha si ťa vyskúšame.",
	event_tutorial_npc_trainer_line_init_answer_accept: "Čo mám robiť?",
	event_tutorial_npc_trainer_line_order: "Tu máš krompáč a vytaž kameň v strede miestnosti.\n\n (I J K L - Použitie nástroja)",
	event_tutorial_npc_trainer_line_final: "Podla štardardizovaných testovacích postupov by som ťa mal teraz pochváliť, ale nato nemáme čas. Pokračuj za manažérom. Verím že je v tvojích silách ho nájsť.",
	event_tutorial_npc_trainer_line_reenter: "Zasa si tu? Máš byť u manažéra!",
	event_tutorial_npc_ambBlocked_name: "Baník CF-520",
	event_tutorial_npc_ambBlocked_line_init: "Bol tu zosun, ale môj krompáč mám na druhej strane. Dúfam že sa niekto uráči to odstrániť.",
	event_tutorial_npc_ambBlocked_line_final: "Vďaka, tu máš 20₪, ja si tu ešte chvíľu posedím.",
	event_tutorial_npc_manager_name: "Manažér",
	event_tutorial_npc_manager_line_init: "Takže $1, konečne si prišieľ. Po tom čo sa stalo som ani neveril, že niekoho z vás ešte pustia do akcie.",
	event_tutorial_npc_manager_line_init_answer_confident: "Mňa tam neudržali.",
	event_tutorial_npc_manager_line_init_answer_smug: "Ako vidíš, som tu.",
	event_tutorial_npc_manager_line_init_answer_suprised: "Ani ja.",
	event_tutorial_npc_manager_line_middle: "No krompáč máš... čo ešte... aha áno, tu máš identifikačnú kartu, prístupový level 2, ale tá ťa zatial ešte nikam nepustí.",
	event_tutorial_npc_manager_line_middle_answer_now: "Čo teraz?",
	event_tutorial_npc_manager_line_final: "Máš slobodu, choď vod ťažiť, alebo sa tu prechádzaj. Platíme za výsledky a nie za čas.",
	misc_enterName: "Prosím vložte meno",
	misc_nothinINearby: "< Nič interaktívne v okolý >",
	mood_annoyed: "Otrávený",
	mood_ironic: "Ironický"
}